config/routes.rb
Aw7s::Application.routes.draw do

  root :to => 'front/home#show'

  devise_for :players, :path => "/", skip: [:sessions,:confirmations, :passwords,:registrations]

  devise_scope :player do
    get     'console/sign_up',  to: 'console/registrations#new',    as: :new_console_registration
    post    'console/sign_up',  to: 'console/registrations#create', as: :console_registration
    get     'console/sign_in',  to: 'console/sessions#new',         as: :new_console_session
    post    'console/sign_in',  to: 'console/sessions#create',      as: :console_session
    delete  'console/sign_out', to: 'console/sessions#destroy',     as: :destroy_console_session
  end

  scope module: :front do 
    get "services/by/:category_code" => "services#by",:as => "services_by"
    
    resources :services, :only => [:index]
    resources :regions, :only => [:index,:show]
    resources :pages, :only => [:index]
  end

  namespace :console do

    get '/' => 'home#show'

    resource :home, :only => [:show] ,controller: :home

    resources :regions do 
      get :list ,:on => :collection
      resources :zones,:except=>[:show]
    end
  
    resources :categories do
      get :list, :on => :collection
    end
    resources :services do 
      get :list , :on => :collection
      get :coverings, :on => :member
    end
    resources :players do 
      collection do
        get :list
      end
    end
    resources :sites
    resources :pages do 
      collection do
        get :list
        put :reload_data
      end
    end
  end

  

  

end

app/models/site.rb
class Site < ActiveRecord::Base

	has_many :pages, :class_name => "Page",
			 :primary_key => "domain", :foreign_key => "domain"

	validates_uniqueness_of :domain,:url

	def self.find_or_create url
		uri = URI(url)
		site = Site.find_by_domain(uri.host)
		url = "#{uri.scheme}://#{uri.host}"
		site = Site.create(:url=>url) unless site
		return site
	end


	before_save do 
		uri = URI(self.url)
		self.domain = uri.host 
		self.url = "#{uri.scheme}://#{self.domain}"
		self.name  = self.domain  unless self.name
	end
end

app/controllers/console/app_controller.rb
#
module Console
class AppController < ApplicationController

	#before_filter :authenticate_player!

	before_filter :require_player

	layout 'console'

	helper_method :current_user,:current_master

	#权限错误提示
	rescue_from CanCan::AccessDenied do |exception|
    	redirect_to  request.referer, :alert => 'Sorry 您没有权限执行这个操作,只有Master可以!'
  	end

	private
	def current_user
		return current_player
	end
	def current_master
		return current_player if current_player && current_player.is_master
	end

	def require_player
	  	unless current_player
	  		flash[:sign_msg] = "请先登录，才能进行操作"
	  	 	session[:to_url] = request.url
	  	 	return redirect_to new_console_session_path  
	  	end
  	end
end
end

app/controllers/console/categories_controller.rb
module Console
class CategoriesController < AppController

	load_and_authorize_resource :class => "Category", except: [:create,:update]

	before_action :require_category,:only => [:show,:edit,:update,:destroy]

	def index
		
	end

	def list
		@categories = Category.all
	end

	def show
		#@category = Category.find_by_id(params[:id])
	end

	def new
		@category = Category.new
	end

	def create
		@category = Category.new(params.require(:category).permit(:code,:name,:en_name))
		if @category.save
			redirect_to list_console_categories_url
		else
			render :action => :new
		end
	end

	def edit

	end

	def update
		if @category.update_attributes(params.require(:category).permit(:name,:en_name))
			redirect_to list_console_categories_url
		else
			render :action => :edit			
		end
	end

	def destroy
		@category.destroy if @category
		respond_to do |format|
	      format.html { redirect_to list_console_categories_url }
	      format.js { }
	      format.json { head :no_content }
	    end
	end



	private

	def require_category
		@category = Category.find_by_id(params[:id])
	end

end

end

app/controllers/console/home_controller.rb
module Console
class HomeController < AppController

	before_filter :require_player ,:except=>[:show]

	def show
		@pages = Page.banner_scope
	end
end
end

app/controllers/console/pages_controller.rb
module Console
class PagesController < AppController

	load_and_authorize_resource :class => "Page",except: [:create,:update]

	def index

	end

	def list
		@pages = Page.all.paginate(:page => params[:page], :per_page => 10)
	end

	def show
		@page = Page.find_by_id(params[:id])
	end

	def new
		@page = Page.new(:published_at=>Date.today)
	end

	def create
		@page = Page.new(params.require(:page).permit(:title,:url,:img_url,:tags,:summary,:original,:is_banner,:is_case,:published_at)) 
		#@page.tag_list = params.require(:page).permit(:tags)[:tags]
		@page.player_id = current_player.id
		@page.player_name = current_player.name
		if @page.save
			redirect_to list_console_pages_path
		else	
			render :action => :new
		end
	end

	def edit
		@page = Page.find_by_id(params[:id])
	end

	def update
		@page = Page.find_by_id(params[:id])
		#@page.tag_list = params.require(:page).permit(:tags)[:tags]
		if @page.update_attributes(params.require(:page).permit(:title,:url,:img_url,:tags,:summary,:original,:is_banner,:is_case,:published_at))
			redirect_to list_console_pages_path
		else
			render :action => :edit
		end
	end

	def destroy
		@page = Page.find_by_id(params[:id])
		return render :js =>'alert("没有这个页面!");' unless @page
		@page.destroy
	end

	def reload_data
		Page.reload_data 
		redirect_to list_console_pages_path
	end
	
end

end

app/controllers/console/pings_controller.rb
module Console
class PingsController < AppController
	
end

end

app/controllers/console/players_controller.rb
module Console

class PlayersController < AppController

	load_and_authorize_resource :class => "Player",except: [:create,:update]

	def index
		
	end

	def list
		@players = Player.all.paginate(:page => params[:page], :per_page => 10)
	end

	def new
		@player = Player.new
	end

	def create
		@player = Player.new(params.require(:player).permit(:name,:email,:phone,:password,:password_confirmation))
		if @player.save
			redirect_to list_console_players_path()
		else
			render :action => :new			
		end
	end

	def edit
		@player = Player.find_by_id(params[:id])
	end

	def update
		@player = Player.find_by_id(params[:id])
	end

	def destroy
		@player = Player.find_by_id(params[:id])
		return render :js =>'alert("没有这个玩家!");' unless @player
		return render :js =>'alert("不能删除当前玩家!");' if @player == current_player
		return render :js =>'alert("不能删除Master玩家!");' if @player.is_master
		@player.destroy
	end

end

end

app/controllers/console/regions_controller.rb
module Console
class RegionsController < AppController

	#
	load_and_authorize_resource :class => "Region",except: [:create,:update]

	before_action :require_region, :only=>[:show,:edit,:update,:destroy]

	def home

	end

	def index
		@regions = Region.all
	end

	def show
		@region = Region.find_by_id(params[:id])
	end

	def list
		@regions = Region.all
	end

	def new
		@region = Region.new
	end

	# require(:person).permit(:name, :age)
	def create
		@region = Region.new(params.require(:region).permit(:code,:name,:en_name,:normal))
		if @region.save
			redirect_to list_console_regions_path()
		else
			render :action => :new			
		end
	end

	def edit

	end

	def update
		if @region.update_attributes(params.require(:region).permit(:name,:en_name,:normal))
			redirect_to list_console_regions_path
		else
			render :action => :edit
		end
	end

	def destroy
		@region.destroy if @region
		respond_to do |format|
	      format.html { redirect_to list_console_regions_path }
	      format.js { }
	      format.json { head :no_content }
	    end
	end

	private

	def require_region
		@region = Region.find_by_id(params[:id])
	end



end

end

app/controllers/console/registrations_controller.rb
module Console
class RegistrationsController < Devise::RegistrationsController

	layout 'console'


	def new
		@player = Player.new
	end

	def create
		@player = Player.new(params.require(:player).permit(:name,:email,:password,:password_confirmation))
		@player.phone = ""
		if @player.save
			sign_in("player",@player)
     		redirect_to console_path
		else
			render :action => :new	
		end
	end

end


end

app/controllers/console/services_controller.rb
module Console

class ServicesController < AppController

	load_and_authorize_resource :class => "Service",except: [:create,:update]

	def home

	end

	def index

	end

	def show
		@service = Service.find_by_id(params[:id])
	end

	def list
		@services = Service.all.paginate(:page => params[:page], :per_page => 10)
	end

	def new
		@service = Service.new
	end


	def create
		@service = Service.new(params.require(:service).permit(:code,:category_code,:name,:full_name,:caption,:normal))
		if @service.save
			redirect_to list_console_services_path()
		else
			render :action => :new			
		end
	end


	def edit
		@service = Service.find_by_id(params[:id])
	end

	def update
		@service = Service.find_by_id(params[:id])

		if @service.update_attributes(params.require(:service).permit(:category_code,:name,:full_name,:caption,:normal))
			redirect_to list_console_services_url
		else
			render :action => :edit			
		end
	end

	def regions
		@service = Service.find_by_id(params[:id])
		@regions = @service.regions
	end

	def coverings
		@service = Service.find_by_id(params[:id])
		@coverings = @service.coverings.includes(:region)
	end


	def destroy
		@service = Service.find_by_id(params[:id])
		@service.destroy if @service
		respond_to do |format|
	      format.html { redirect_to list_console_regions_path }
	      format.js { }
	      format.json { head :no_content }
	    end
	end

end

end

app/controllers/console/sessions_controller.rb
module Console
class SessionsController < Devise::SessionsController

	layout 'console'

	def new
		@player = Player.new
	end

	def create
		resource = warden.authenticate!(:scope => resource_name, :recall => "#{controller_path}#new")
    	sign_in(resource_name, resource)
    	to_url = session[:to_url]
    	return redirect_to console_path unless to_url
    	session[:to_url] = nil
		redirect_to console_path
	end

	def destroy
		sign_out()
		redirect_to new_console_session_path 
	end


end

end

app/controllers/console/sites_controller.rb
module Console
class SitesController < AppController

	load_and_authorize_resource :class => "Site",except: [:create,:update]

	def index
		@site  = Site.new
		@sites = Site.all
		@action = "create"
	end

	def show

	end

	def new
		@site = Site.new
		render :layout=>nil
	end

	def create
		@site = Site.new(params.require(:site).permit(:name,:url,:normal))
		if @site.save
			redirect_to console_sites_path()
		else
			render :action => :index
		end
	end

	def edit
		@site = Site.find_by_id(params[:id])
		render :layout=>nil
	end

	def update
		@site = Site.find_by_id(params[:id])
		@sites = Site.all
		if @site.update_attributes(params.require(:site).permit(:name,:url,:normal))
			redirect_to console_sites_path()
		else
			render :action => :index
		end
	end

	def destroy
		@site = Site.find_by_id(params[:id])
		return render :js =>'alert("没有这个网站!");' unless @site
		@site.destroy
	end

	
end

end

app/controllers/console/zones_controller.rb
module Console
class ZonesController < AppController

	load_and_authorize_resource :class => "Zone",except: [:create,:update]

	before_action :require_region
	before_action :require_region_zones #,:only=>[:index,:edit]

	def index
		@zone  = Zone.new
		@action = "create"
		@zones = @region.zones
	end

	def create		
		@region.zones.build(params.require(:zone).permit(:code,:remark,:normal))
		if @region.save
			redirect_to console_region_zones_path(@region)
		else
			render :action => :index
		end
	end

	def edit
		@zone = @region.zones.find_by_id(params[:id])
		@action = "update"
		render :template => "console/zones/index" 
	end

	def update
		@zone = @region.zones.find_by_id(params[:id])
		if @zone.update_attributes(params.require(:zone).permit(:code,:remark,:normal))
			redirect_to console_region_zones_path(@region)
		else
			render :action => :edit
		end
	end

	def destroy
		@zone = @region.zones.find_by_id(params[:id])
		@zone.destroy if @zone
	end

	private 
	def require_region
		@region = Region.find_by_id(params[:region_id])
	end

	def require_region_zones
		@zones = @region.zones
	end

end
end

app/views/console/sites/_dialog_form.html.erb
<div class="modal-dialog" id="site-dialog">
<%= form_for [:console,@site], :url => {:controller => "sites",:action=>action},:html=>{:class=>"form form-inline"} do |form| %>
<div class="modal-content">
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
  <h4 class="modal-title"><%= title || "" %></h4>
</div>
<div class="modal-body">
 	 <label><%= action_name == "edit" ? "修改网站" : "新增网站" %>:</label>
	<div class="form-group">
	<label class="sr-only" for="">网站名称</label>
	<%= form.text_field :name,:placeholder=>"网站名称",:class=>"form-control",:required=>"required"  %>
	</div>
	<div class="form-group">
	<label class="sr-only" for="">URL</label>
	<%= form.url_field :url,:placeholder=>"url",:class=>"form-control",:required=>"required"  %>
	</div>
	<div class="checkbox">
	<label>
	  <%= form.check_box :normal %>状态正常
	</label>
	</div>
</div>
<div class="modal-footer">
	 <%= form.submit :"提 交",:class=>"btn btn-primary" %>
  	<button type="button" class="btn btn-default" data-dismiss="modal">取 消</button>
</div>
</div>

<%end%>

</div>


<script type="text/javascript">

</script>

app/views/console/sites/_table.html.erb
<table class="table">
<thead>
<tr>
<td colspan="5">

</td>
<td colspan="" class="text-right">
<a class="btn btn-primary" data-toggle="modal" data-target="#siteModal" href="<%= new_console_site_path%>">
	添加网站
</a>
</td>
</tr>
<tr>
	<td>名称</td>
	<td>URL</td>
	<td>域名</td>
	<td>文章数量</td>
	<td>状态</td>
	<td class="text-right">操作</td>
</tr>
</thead>
<tbody>
<% @sites.each do |site|%>
<tr data-id="<%=site.id %>">
<td><%= site.name %></td>
<td><%= link_to site.url,site.url,:target=>"_blank" %></td>
<td><%= site.domain %></td>
<td><%= site.pages_count %></td>
<td><%= site.normal ? "Yes" : "No" %></td>
<td class="text-right">
<div class="btn-group btn-group-sm text-left">
<button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
	操 作 <span class="caret"></span>
</button>
<ul class="dropdown-menu" role="menu">
<li>
	<%= link_to raw('<i class="glyphicon glyphicon-edit"></i> 修改'),edit_console_site_path(site),:'data-toggle'=>"modal", :'data-target'=>"#siteModal#{site.id}" %>
</li>
<% if can? :destroy, site %>
<li>
<%= link_to raw('<i class="glyphicon glyphicon-trash"></i> 删除'),console_site_path(site),:method=>:delete,:format=>"js",:remote=>true,:data => { :confirm => 'Are you sure?' } %>
</li>
<%end%>
</ul>
</div>
<div class="modal fade text-left" id="siteModal<%= site.id %>" tabindex="-1" role="dialog"  >
</div>
</td>
</tr>
<%end%>
</tbody>
</table>

app/views/console/sites/destroy.js.erb
<% if @site.destroyed? %>
$("tr[data-id=<%= @site.id %>]").fadeOut(500);
<%else%>
alert("fail");
<%end%>

app/views/console/sites/edit.html.erb
<%= render :partial =>"dialog_form",:locals=>{:action=>"update",:title => "修改网站"}%>

app/views/console/sites/index.html.erb
<%= render 'console/pages/navbar' %>
<div class="panel panel-primary">
<div class="panel-heading">
  <h3 class="panel-title">网站管理</h3>
</div>
<div class="panel-body">
<%= render "table" %>
</div>
</div>

<!-- modal -->
<div class="modal fade" id="siteModal" tabindex="-1" role="dialog"  >
</div>
<!-- /.modal -->

<script type="text/javascript">

</script>

app/views/console/sites/new.html.erb
<%= render :partial =>"dialog_form",:locals=>{:action=>"create",:title => "新建网站"}%>