config/routes.rb
Aw7s::Application.routes.draw do

  root :to => 'front/home#show'

  devise_for :players, :path => "/", skip: [:sessions,:confirmations, :passwords,:registrations]

  devise_scope :player do
    get     'console/sign_up',  to: 'console/registrations#new',    as: :new_console_registration
    post    'console/sign_up',  to: 'console/registrations#create', as: :console_registration
    get     'console/sign_in',  to: 'console/sessions#new',         as: :new_console_session
    post    'console/sign_in',  to: 'console/sessions#create',      as: :console_session
    delete  'console/sign_out', to: 'console/sessions#destroy',     as: :destroy_console_session
  end

  scope module: :front do 
    get "services/by/:category_code" => "services#by",:as => "services_by"
    
    resources :services, :only => [:index]
    resources :regions, :only => [:index,:show]
    resources :pages, :only => [:index]
  end

  namespace :console do

    get '/' => 'home#show'

    resource :home, :only => [:show] ,controller: :home

    resources :regions do 
      get :list ,:on => :collection
      resources :zones,:except=>[:show]
    end
  
    resources :categories do
      get :list, :on => :collection
    end
    resources :services do 
      get :list , :on => :collection
      get :coverings, :on => :member
    end
    resources :players do 
      collection do
        get :list
      end
    end
    resources :sites
    resources :pages do 
      collection do
        get :list
        put :reload_data
      end
    end
  end

  

  

end

app/models/region.rb
class Region < ActiveRecord::Base
	#
	has_many :zones, :class_name => "Zone",
			 :primary_key => "code", :foreign_key => "region_code"
	#
	has_many :coverings, :class_name => 'Covering',
			 :primary_key => "code", :foreign_key => "region_code"
	#
	has_many :services,:class_name => 'Service',
			 :primary_key => 'code',:foreign_key => 'region_code',through: :coverings

	validates_presence_of :code,:name
  	validates_uniqueness_of :code,:name

	
	def code_name
		"#{self.code} / #{self.name}"
	end

	def full_name
		"#{self.name} #{self.name_en}"
	end

end

app/controllers/console/app_controller.rb
#
module Console
class AppController < ApplicationController

	#before_filter :authenticate_player!

	before_filter :require_player

	layout 'console'

	helper_method :current_user,:current_master

	#权限错误提示
	rescue_from CanCan::AccessDenied do |exception|
    	redirect_to  request.referer, :alert => 'Sorry 您没有权限执行这个操作,只有Master可以!'
  	end

	private
	def current_user
		return current_player
	end
	def current_master
		return current_player if current_player && current_player.is_master
	end

	def require_player
	  	unless current_player
	  		flash[:sign_msg] = "请先登录，才能进行操作"
	  	 	session[:to_url] = request.url
	  	 	return redirect_to new_console_session_path  
	  	end
  	end
end
end

app/controllers/console/categories_controller.rb
module Console
class CategoriesController < AppController

	load_and_authorize_resource :class => "Category", except: [:create,:update]

	before_action :require_category,:only => [:show,:edit,:update,:destroy]

	def index
		
	end

	def list
		@categories = Category.all
	end

	def show
		#@category = Category.find_by_id(params[:id])
	end

	def new
		@category = Category.new
	end

	def create
		@category = Category.new(params.require(:category).permit(:code,:name,:en_name))
		if @category.save
			redirect_to list_console_categories_url
		else
			render :action => :new
		end
	end

	def edit

	end

	def update
		if @category.update_attributes(params.require(:category).permit(:name,:en_name))
			redirect_to list_console_categories_url
		else
			render :action => :edit			
		end
	end

	def destroy
		@category.destroy if @category
		respond_to do |format|
	      format.html { redirect_to list_console_categories_url }
	      format.js { }
	      format.json { head :no_content }
	    end
	end



	private

	def require_category
		@category = Category.find_by_id(params[:id])
	end

end

end

app/controllers/console/home_controller.rb
module Console
class HomeController < AppController

	before_filter :require_player ,:except=>[:show]

	def show
		@pages = Page.banner_scope
	end
end
end

app/controllers/console/pages_controller.rb
module Console
class PagesController < AppController

	load_and_authorize_resource :class => "Page",except: [:create,:update]

	def index

	end

	def list
		@pages = Page.all.paginate(:page => params[:page], :per_page => 10)
	end

	def show
		@page = Page.find_by_id(params[:id])
	end

	def new
		@page = Page.new(:published_at=>Date.today)
	end

	def create
		@page = Page.new(params.require(:page).permit(:title,:url,:img_url,:tags,:summary,:original,:is_banner,:is_case,:published_at)) 
		#@page.tag_list = params.require(:page).permit(:tags)[:tags]
		@page.player_id = current_player.id
		@page.player_name = current_player.name
		if @page.save
			redirect_to list_console_pages_path
		else	
			render :action => :new
		end
	end

	def edit
		@page = Page.find_by_id(params[:id])
	end

	def update
		@page = Page.find_by_id(params[:id])
		#@page.tag_list = params.require(:page).permit(:tags)[:tags]
		if @page.update_attributes(params.require(:page).permit(:title,:url,:img_url,:tags,:summary,:original,:is_banner,:is_case,:published_at))
			redirect_to list_console_pages_path
		else
			render :action => :edit
		end
	end

	def destroy
		@page = Page.find_by_id(params[:id])
		return render :js =>'alert("没有这个页面!");' unless @page
		@page.destroy
	end

	def reload_data
		Page.reload_data 
		redirect_to list_console_pages_path
	end
	
end

end

app/controllers/console/pings_controller.rb
module Console
class PingsController < AppController
	
end

end

app/controllers/console/players_controller.rb
module Console

class PlayersController < AppController

	load_and_authorize_resource :class => "Player",except: [:create,:update]

	def index
		
	end

	def list
		@players = Player.all.paginate(:page => params[:page], :per_page => 10)
	end

	def new
		@player = Player.new
	end

	def create
		@player = Player.new(params.require(:player).permit(:name,:email,:phone,:password,:password_confirmation))
		if @player.save
			redirect_to list_console_players_path()
		else
			render :action => :new			
		end
	end

	def edit
		@player = Player.find_by_id(params[:id])
	end

	def update
		@player = Player.find_by_id(params[:id])
	end

	def destroy
		@player = Player.find_by_id(params[:id])
		return render :js =>'alert("没有这个玩家!");' unless @player
		return render :js =>'alert("不能删除当前玩家!");' if @player == current_player
		return render :js =>'alert("不能删除Master玩家!");' if @player.is_master
		@player.destroy
	end

end

end

app/controllers/console/regions_controller.rb
module Console
class RegionsController < AppController

	#
	load_and_authorize_resource :class => "Region",except: [:create,:update]

	before_action :require_region, :only=>[:show,:edit,:update,:destroy]

	def home

	end

	def index
		@regions = Region.all
	end

	def show
		@region = Region.find_by_id(params[:id])
	end

	def list
		@regions = Region.all
	end

	def new
		@region = Region.new
	end

	# require(:person).permit(:name, :age)
	def create
		@region = Region.new(params.require(:region).permit(:code,:name,:en_name,:normal))
		if @region.save
			redirect_to list_console_regions_path()
		else
			render :action => :new			
		end
	end

	def edit

	end

	def update
		if @region.update_attributes(params.require(:region).permit(:name,:en_name,:normal))
			redirect_to list_console_regions_path
		else
			render :action => :edit
		end
	end

	def destroy
		@region.destroy if @region
		respond_to do |format|
	      format.html { redirect_to list_console_regions_path }
	      format.js { }
	      format.json { head :no_content }
	    end
	end

	private

	def require_region
		@region = Region.find_by_id(params[:id])
	end



end

end

app/controllers/console/registrations_controller.rb
module Console
class RegistrationsController < Devise::RegistrationsController

	layout 'console'


	def new
		@player = Player.new
	end

	def create
		@player = Player.new(params.require(:player).permit(:name,:email,:password,:password_confirmation))
		@player.phone = ""
		if @player.save
			sign_in("player",@player)
     		redirect_to console_path
		else
			render :action => :new	
		end
	end

end


end

app/controllers/console/services_controller.rb
module Console

class ServicesController < AppController

	load_and_authorize_resource :class => "Service",except: [:create,:update]

	def home

	end

	def index

	end

	def show
		@service = Service.find_by_id(params[:id])
	end

	def list
		@services = Service.all.paginate(:page => params[:page], :per_page => 10)
	end

	def new
		@service = Service.new
	end


	def create
		@service = Service.new(params.require(:service).permit(:code,:category_code,:name,:full_name,:caption,:normal))
		if @service.save
			redirect_to list_console_services_path()
		else
			render :action => :new			
		end
	end


	def edit
		@service = Service.find_by_id(params[:id])
	end

	def update
		@service = Service.find_by_id(params[:id])

		if @service.update_attributes(params.require(:service).permit(:category_code,:name,:full_name,:caption,:normal))
			redirect_to list_console_services_url
		else
			render :action => :edit			
		end
	end

	def regions
		@service = Service.find_by_id(params[:id])
		@regions = @service.regions
	end

	def coverings
		@service = Service.find_by_id(params[:id])
		@coverings = @service.coverings.includes(:region)
	end


	def destroy
		@service = Service.find_by_id(params[:id])
		@service.destroy if @service
		respond_to do |format|
	      format.html { redirect_to list_console_regions_path }
	      format.js { }
	      format.json { head :no_content }
	    end
	end

end

end

app/controllers/console/sessions_controller.rb
module Console
class SessionsController < Devise::SessionsController

	layout 'console'

	def new
		@player = Player.new
	end

	def create
		resource = warden.authenticate!(:scope => resource_name, :recall => "#{controller_path}#new")
    	sign_in(resource_name, resource)
    	to_url = session[:to_url]
    	return redirect_to console_path unless to_url
    	session[:to_url] = nil
		redirect_to console_path
	end

	def destroy
		sign_out()
		redirect_to new_console_session_path 
	end


end

end

app/controllers/console/sites_controller.rb
module Console
class SitesController < AppController

	load_and_authorize_resource :class => "Site",except: [:create,:update]

	def index
		@site  = Site.new
		@sites = Site.all
		@action = "create"
	end

	def show

	end

	def new
		@site = Site.new
		render :layout=>nil
	end

	def create
		@site = Site.new(params.require(:site).permit(:name,:url,:normal))
		if @site.save
			redirect_to console_sites_path()
		else
			render :action => :index
		end
	end

	def edit
		@site = Site.find_by_id(params[:id])
		render :layout=>nil
	end

	def update
		@site = Site.find_by_id(params[:id])
		@sites = Site.all
		if @site.update_attributes(params.require(:site).permit(:name,:url,:normal))
			redirect_to console_sites_path()
		else
			render :action => :index
		end
	end

	def destroy
		@site = Site.find_by_id(params[:id])
		return render :js =>'alert("没有这个网站!");' unless @site
		@site.destroy
	end

	
end

end

app/controllers/console/zones_controller.rb
module Console
class ZonesController < AppController

	load_and_authorize_resource :class => "Zone",except: [:create,:update]

	before_action :require_region
	before_action :require_region_zones #,:only=>[:index,:edit]

	def index
		@zone  = Zone.new
		@action = "create"
		@zones = @region.zones
	end

	def create		
		@region.zones.build(params.require(:zone).permit(:code,:remark,:normal))
		if @region.save
			redirect_to console_region_zones_path(@region)
		else
			render :action => :index
		end
	end

	def edit
		@zone = @region.zones.find_by_id(params[:id])
		@action = "update"
		render :template => "console/zones/index" 
	end

	def update
		@zone = @region.zones.find_by_id(params[:id])
		if @zone.update_attributes(params.require(:zone).permit(:code,:remark,:normal))
			redirect_to console_region_zones_path(@region)
		else
			render :action => :edit
		end
	end

	def destroy
		@zone = @region.zones.find_by_id(params[:id])
		@zone.destroy if @zone
	end

	private 
	def require_region
		@region = Region.find_by_id(params[:region_id])
	end

	def require_region_zones
		@zones = @region.zones
	end

end
end

app/controllers/front/regions_controller.rb
module Front
class RegionsController < AppController
	
	def index
		@regions = Region.all
	end

	def show
		@region = Region.find_by_code(params[:id])
		@zones = @region.zones if @region
		render :layout=>nil
	end

		
end
end

app/views/console/regions/_form.html.erb
<% if @region.errors.any? %>
<div class="alert alert-block alert-danger fade in">
<button type="button" class="close" data-dismiss="alert">×</button>
<h4 class="alert-heading">
  <%= pluralize(@region.errors.count, "错误") %> 地区被禁止保存
</h4>
<ul>
<% @region.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
<% end %>
</ul>
</div>
<% end %>


<%= form_for [:console,@region],:html=>{:class=>"form form-horizontal",:role=>"form",:id=>"region-form"} do |form| %>
<div class="form-group">
  <label for="" class="col-lg-2 control-label">地区代码:</label>
  <div class="col-lg-3">
    <%= form.text_field :code,:placeholder=>"代码",:class=>"form-control",:required=>"required" %>
  </div>
</div>
<div class="form-group">
  <label for="" class="col-lg-2 control-label">地区名称:</label>
  <div class="col-lg-3">
     <%= form.text_field :name,:placeholder=>"名称",:class=>"form-control",:required=>"required" %>
  </div>
</div>
<div class="form-group">
  <label for="" class="col-lg-2 control-label">英文名称:</label>
  <div class="col-lg-3">
    <%= form.text_field :en_name,:placeholder=>"英文名称",:class=>"form-control" %>
  </div>
</div>
<div class="form-group">
  <label for="" class="col-lg-2 control-label">正常运行:</label>
  <div class="checkbox col-lg-3">
   <label>
    <%= form.check_box :normal %> 状态正常
    </label>
  </div>
</div>

<div class="form-group">
  <div class="col-lg-offset-2 col-lg-10">
     <%= form.submit :"提 交",:class=>"btn btn-primary" %>
     <%= link_to "返回列表", list_console_regions_path %>
  </div>
</div>
<%end%>
<script type="text/javascript">
$("#region-form").validate();
</script>

app/views/console/regions/_navbar_collection.html.erb
<ul class="nav nav-tabs">
<li <%= active_class if action_name == "index" %>>
 <%= link_to raw('<span class="glyphicon glyphicon-home"></span> 地区主页'),console_regions_path%>
</li>
<li <%= active_class if action_name == "list" %>>
 <%= link_to raw('<span class="glyphicon glyphicon-list"></span> 地区列表'),list_console_regions_path%>
</li>
<li <%= active_class if action_name == "new" %>>
 <%= link_to raw('<span class="glyphicon glyphicon-plus"></span> 新建地区'),new_console_region_path %>
</li>

</ul>

app/views/console/regions/_navbar_member.html.erb
<ul class="nav nav-tabs">
<li>
<%= link_to raw('<i class="glyphicon glyphicon-arrow-left"></i>返回'),list_console_regions_path()%>
</li>

<li <%= active_class if controller_name == "regions" && action_name == "show" %>>
 <%= link_to raw('<i class="glyphicon glyphicon-file"></i>基本信息'),console_region_path(@region)%>
</li>
<li <%= active_class if controller_name == "regions" && action_name == "edit" %>>
 <%= link_to raw('<i class="glyphicon glyphicon-edit"></i>修改信息'),edit_console_region_path(@region) %>
</li>
<li <%= active_class if controller_name == "zones" %>>
<%= link_to raw('<i class="glyphicon glyphicon-map-marker"></i>可用区域'),console_region_zones_path(@region)%>
</li>
</ul>

app/views/console/regions/_table.html.erb
<table class="table">
<thead>
<tr>
	<td>代码</td>
	<td>地址</td>
	<td>Http Ping</td>
	<td>平均速度</td>
	<td>可用区域</td>
	<td>操作</td>
</tr>
</thead>
<tbody>
<% regions.each do |region|%>
<tr data-id="<%= region.id%>">
	<td><%= link_to region.code,console_region_path(region) %></td>
	<td><%= region.name %> <%= region.en_name%> </td>
	<td><%= region.ping_count%></td>
	<td><%= region.avg_speed %> ms

	</td>
	<td>
	<% if region.zones_count == 0  %>
		<a href="<%= console_region_zones_path(region)%>" class="btn btn-sm btn-danger"><%= "#{region.zones_count}个可用区域" %></a>
	<%else%>
		<div class="btn-group btn-group-sm">
        <%= link_to raw("<b>#{region.zones_count}</b>个可用区域"),console_region_zones_path(region),:class=>"btn btn-info btn-small" %>
        <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown"><span class="caret"></span></button>
        <ul class="dropdown-menu" role="menu">
          <% region.zones.each do |zone| %>
			<li><%= link_to zone.code,console_region_zones_path(region)%></li>
			<%end%>
        </ul>
      </div>
	<%end%>
	</td>
	<td>
		<div class="btn-group btn-group-sm">
		  <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
		    操 作 <span class="caret"></span>
		  </button>
		  <ul class="dropdown-menu" role="menu">
		   <li>
		   		<%= link_to raw('<i class="glyphicon glyphicon-edit"></i> 修改'),edit_console_region_path(region) %>
		   </li>
		   <% if can? :destroy, region %>
		   <li>
				<%= link_to raw('<i class="glyphicon glyphicon-trash"></i> 删除'),console_region_path(region),:method=>:delete,:format=>"js",:remote=>true,:data => { :confirm => 'Are you sure?' } %>
			</li>
			<%end%>
		  </ul>
		</div>
	</td>
</tr>
<%end%>
</tbody>
</table>

app/views/console/regions/destroy.js.erb
<% if @region.destroyed? %>
//$("tr[data-id=<%= @region.id %>]").remove();
$("tr[data-id=<%= @region.id %>]").fadeOut(500);
<%else%>
alert("fail");
<%end%>

app/views/console/regions/edit.html.erb
<%= render :partial => "navbar_member"%>


<div class="panel panel-primary">
<div class="panel-heading">
  <h3 class="panel-title">修改地区</h3>
</div>
<div class="panel-body">
  <%= render :partial => "form" %>
</div>
</div>

app/views/console/regions/index.html.erb
<%= render :partial => "navbar_collection"%>

<div class="panel panel-primary">
    <div class="panel-heading">
      <h3 class="panel-title">地区主页</h3>
    </div>
    <div class="panel-body">
      目前AWS已全球覆盖<%= link_to  Region.all.count,list_console_regions_path %>个地区,您个可以根据您的需求选择不同地区的服务.
      <p>
      	<a href="http://aws.amazon.com/" target="_blank">Amazon Web Services™</a>
      </p>
    </div>
  </div>

app/views/console/regions/list.html.erb
<%= render :partial => "navbar_collection"%>
<div class="panel panel-primary">
<div class="panel-heading">
  <h3 class="panel-title">地区列表</h3>
</div>
<div class="panel-body">
<%= render :partial =>"table",:locals=>{:regions => @regions} %>
</div>
</div>

app/views/console/regions/new.html.erb
<%= render :partial => "navbar_collection"%>


<div class="panel panel-primary">
<div class="panel-heading">
  <h3 class="panel-title">新建地区</h3>
</div>
<div class="panel-body">
  <%= render :partial => "form" %>
</div>
</div>

app/views/console/regions/show.html.erb
<%= render :partial => "navbar_member"%>
<div class="panel panel-primary">
<div class="panel-heading">
  <h3 class="panel-title"><%= @region.code %></h3>
</div>
<div class="panel-body">
<p>代码: <%= @region.code %><p/>
<p>名称: <%= @region.name %> <%= @region.en_name%> <p/>
<p>
<% if @region.zones_count == 0  %>
<a href="<%= console_region_zones_path(@region)%>" class="btn btn-sm btn-danger"><%= "#{@region.zones_count}个可用区域" %></a>
<%else%>
	<div class="btn-group btn-group-sm">
    <%= link_to raw("<b>#{@region.zones_count}</b>个可用区域"),console_region_zones_path(@region),:class=>"btn btn-info btn-small" %>
    <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown"><span class="caret"></span></button>
    <ul class="dropdown-menu" role="menu">
      <% @region.zones.each do |zone| %>
		<li><%= link_to zone.code,console_region_zones_path(@region)%></li>
		<%end%>
    </ul>
  </div>
<%end%>
 <p/>
</div>
</div>